### ISSUE TITLE
spawn openssl ENOENT on azure app service (windows). 

### ISSUE THREAD

**Issue by tony-gutierrez** [mgcrea/node-openssl-wrapper#22]
I'm getting a ENONET error on Azure. 

Perhaps we could make the "spawn" attribute public so that users could replace it with something like this: https://github.com/moxystudio/node-cross-spawn?

**Comment by nao3301** [comment]
getting same Error on Wondows 10 machine:

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn openssl ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by marianozunino** [comment]
You can specify the path in with this pkg.
https://www.npmjs.com/package/openssl-ts
